In [91]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd


In [92]:
df = pd.read_excel('../dataset/IPM.xlsx')

In [93]:
df.head()

Harapan_Lama_Sekolah,Pengeluaran_Perkapita,Rerata_Lama_Sekolah,Usia_Harapan_Hidup,IPM
0                         14.36,9572,9.37,69.96,High                                   
1                        13.9,7148,9.48,65.28,Normal                                   
2                       14.32,8776,8.68,67.43,Normal                                   
3                         14.6,8180,8.88,64.4,Normal                                   
4                       14.01,8030,9.67,68.22,Normal

In [69]:
df[['Harapan_Lama_Sekolah','Pengeluaran_Perkapita','Rerata_Lama_Sekolah','Usia_Harapan_Hidup','IPM']] = pd.DataFrame(df['Harapan_Lama_Sekolah,Pengeluaran_Perkapita,Rerata_Lama_Sekolah,Usia_Harapan_Hidup,IPM'].str.split(',').tolist())

In [70]:
df.head()

Harapan_Lama_Sekolah,Pengeluaran_Perkapita,Rerata_Lama_Sekolah,Usia_Harapan_Hidup,IPM  \
0                         14.36,9572,9.37,69.96,High                                      
1                        13.9,7148,9.48,65.28,Normal                                      
2                       14.32,8776,8.68,67.43,Normal                                      
3                         14.6,8180,8.88,64.4,Normal                                      
4                       14.01,8030,9.67,68.22,Normal                                      

  Harapan_Lama_Sekolah Pengeluaran_Perkapita Rerata_Lama_Sekolah  \
0                14.36                  9572                9.37   
1                 13.9                  7148                9.48   
2                14.32                  8776                8.68   
3                 14.6                  8180                8.88   
4                14.01                  8030                9.67   

  Usia_Harapan_Hidup     IPM  
0              69.96    High  
1              65.28  Normal  
2              67.43  Normal  
3               64.4  Normal  
4              68.22  Normal

In [71]:
df.drop(['Harapan_Lama_Sekolah,Pengeluaran_Perkapita,Rerata_Lama_Sekolah,Usia_Harapan_Hidup,IPM'], axis=1, inplace=True)

In [72]:
df.head()

Harapan_Lama_Sekolah Pengeluaran_Perkapita Rerata_Lama_Sekolah  \
0                14.36                  9572                9.37   
1                 13.9                  7148                9.48   
2                14.32                  8776                8.68   
3                 14.6                  8180                8.88   
4                14.01                  8030                9.67   

  Usia_Harapan_Hidup     IPM  
0              69.96    High  
1              65.28  Normal  
2              67.43  Normal  
3               64.4  Normal  
4              68.22  Normal

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196 entries, 0 to 2195
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Harapan_Lama_Sekolah   2196 non-null   object
 1   Pengeluaran_Perkapita  2196 non-null   object
 2   Rerata_Lama_Sekolah    2196 non-null   object
 3   Usia_Harapan_Hidup     2196 non-null   object
 4   IPM                    2196 non-null   object
dtypes: object(5)
memory usage: 85.9+ KB


In [74]:
df.describe()

Harapan_Lama_Sekolah Pengeluaran_Perkapita Rerata_Lama_Sekolah  \
count                  2196                  2196                2196   
unique                  499                  1930                 633   
top                   12.83                  7980                7.86   
freq                     20                     4                  14   

       Usia_Harapan_Hidup     IPM  
count                2196    2196  
unique               1054       4  
top                  71.6  Normal  
freq                    9    1128

## EDA

## MODELING

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, confusion_matrix,roc_curve, auc, \
roc_auc_score, precision_score, recall_score, precision_recall_curve
from sklearn.model_selection import cross_validate, cross_val_score, train_test_split
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0)
from sklearn.svm import LinearSVC
lsvc = LinearSVC(random_state=0)
from sklearn.preprocessing import LabelEncoder

In [76]:
df

Harapan_Lama_Sekolah Pengeluaran_Perkapita Rerata_Lama_Sekolah  \
0                   14.36                  9572                9.37   
1                    13.9                  7148                9.48   
2                   14.32                  8776                8.68   
3                    14.6                  8180                8.88   
4                   14.01                  8030                9.67   
...                   ...                   ...                 ...   
2191                10.13                  5522                4.91   
2192                 7.11                  5440                2.51   
2193                 9.79                  4761                2.99   
2194                14.99                 14922                11.3   
2195                12.91                 11059                8.17   

     Usia_Harapan_Hidup     IPM  
0                 69.96    High  
1                 65.28  Normal  
2                 67.43  Normal  
3                  64.4  Normal  
4                 68.22  Normal  
...                 ...     ...  
2191              65.32     Low  
2192              65.26     Low  
2193              64.83     Low  
2194              70.15    High  
2195               71.2    High  

[2196 rows x 5 columns]

In [77]:
df.corr()

Empty DataFrame
Columns: []
Index: []

In [78]:
le = LabelEncoder()

In [79]:
df['IPM'] = le.fit_transform(df['IPM'])

In [80]:
X = df.drop(['IPM'], axis= 1)
y = df['IPM']

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 42)

In [82]:
rfc = RandomForestClassifier(n_estimators= 100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [83]:
y_pred = rfc.predict(X_test)

In [84]:
from sklearn.metrics import mean_absolute_error
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))
print('accuracy train :', accuracy_score(y_true=y_train, y_pred= rfc.predict(X_train)))
print('Accuracy:', accuracy_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))

Confusion Matrix:
 [[159   0   3   2]
 [  0  15   1   0]
 [  4   0 223   0]
 [  1   0   0  32]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97       164
           1       1.00      0.94      0.97        16
           2       0.98      0.98      0.98       227
           3       0.94      0.97      0.96        33

    accuracy                           0.97       440
   macro avg       0.97      0.96      0.97       440
weighted avg       0.98      0.97      0.98       440

accuracy train : 1.0
Accuracy: 0.975
Mean Absolute Error: 0.05454545454545454


In [85]:
adb = AdaBoostClassifier()

In [86]:
adb.fit(X_train, y_train)

AdaBoostClassifier()

In [87]:
y_pred = adb.predict(X_test)

In [89]:
from sklearn.metrics import mean_absolute_error
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))
print('accuracy train :', accuracy_score(y_true=y_train, y_pred= rfc.predict(X_train)))
print('Accuracy:', accuracy_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))

Confusion Matrix:
 [[127   0  37   0]
 [  0  16   0   0]
 [ 35  15 177   0]
 [ 33   0   0   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.77      0.71       164
           1       0.52      1.00      0.68        16
           2       0.83      0.78      0.80       227
           3       0.00      0.00      0.00        33

    accuracy                           0.73       440
   macro avg       0.50      0.64      0.55       440
weighted avg       0.69      0.73      0.70       440

accuracy train : 1.0
Accuracy: 0.7272727272727273
Mean Absolute Error: 0.5863636363636363


c:\Users\nuvolaofficial\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\nuvolaofficial\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\nuvolaofficial\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this beh